### PR TITLE
ESP8266 friendly tweaks

### PR DESCRIPTION
**Pull request by shaneapowell**
I had to make a couple of pretty minor changes to have your AES library be compatible with my ESP8266 board.  Thought I'd share the changes with you in case you want to add support for the ESP board.  So far I've only tested encryption.  I'll let you know once I get a chance to also test decryption.

### CODE REVIEW

**Comment by spaniakos** [comment]
thank you for the info. 
i will test the changes on Monday and hopefully commit the changes.

**Comment by shaneapowell** [comment]
Just a heads up.. both encryption and decryption work fine on my ESP8266 board.  Granted, the payloads I'm dealing with are only about 500 bytes in size, but the performance is very fast on this little board too.

**Comment by jfresen** [comment]
Just wondering: I had to guard the line with `fdevopen` in printf.h with `#if define(ESP8266)` as well, otherwise it wouldn't compile for me when building for the ESP8266. How come you didn't have to do this?

**Comment by shaneapowell** [comment]
That's a good question.  Could have something to do with my using PlatformIO to compile for my ESP8266?   Perhaps my environment blocks that fdevopen line with the #ifdef on line 20.  I'll try and take a look and see what is different.

**Comment by spaniakos** [comment]
Its library specific error.
I will try to identofy it aftet i get from web summit.

**Comment by jfresen** [comment]
Any updates? I would like to know if my fix is correct (see jfresen/AES@5770ea79b299e24a9bddc4ec49f629d8d258177e).

**Comment by jfresen** [comment]
BTW, I'm looking at some other forks now and I see this commit tcz001/AES@4291efeaab863726e1ca9638c80103f557b3efaf. I haven't checked it out yet, but it looks like it will be a more generic fix for the problem of the avr include. Maybe worth checking that out and using that fix instead?

**Comment by spaniakos** [comment]
yes,
it looks like tha tcz001 fix is more generic and would work with most
machines.

**Comment by spaniakos** [comment]
@shaneapowell  i saw again your fixes.
consider the following :

#elif defined ( ESP8266 )
  #include <pgmspace.h>
  #define PSTR(x) (x)
#else

instead of adding all different kind of printf for your board.
if it works on your board, please make a new pull request and i will add it.

**Comment by shaneapowell** [comment]
Indeed... you're cleaner suggestion seems to compile and work just fine.

**Pull request merged**
